###получить всех сотрудников
GET http://localhost:8080/employees

### создать сотрудника
POST http://localhost:8080/employees
Content-Type: application/json

{
"firstName":"test",
"lastName":"test",
"department":1,
"salary":1000
}

### создать сотрудника2
POST http://localhost:8080/employees
Content-Type: application/json

{
"firstName":"test2",
"lastName":"test2",
"department":2,
"salary":3000
}

###получить сумму зарплат по сотрудникам
GET http://localhost:8080/employees/salary/sum

###получить сотрудника с минимальной зарплатой
GET http://localhost:8080/employees/salary/min

###получить сотрудника с максимальной зарплатой
GET http://localhost:8080/employees/salary/max

###получить всех сотрудников, зарплата которых больше средней
GET http://localhost:8080/employees/high-salary

###возвращает список сотрудников по департаменту
GET http://localhost:8080/department/{id}/employees

###возвращает сумму зарплат по департаменту
GET http://localhost:8080/department/{id}/salary/sum

###возвращает максимальную зарплату по департаменту
GET http://localhost:8080/department/{id}/salary/max

###возвращает минимальную зарплату по департаменту
GET http://localhost:8080/department/{id}/salary/min

###возвращает сотрудников, сгруппированых по отделам
GET http://localhost:8080/department/employees